import os
from fpdf import FPDF
from datetime import datetime

class PDFReportGenerator:
    def __init__(self, user_name: str, destination: str):
        self.pdf = FPDF()
        self.pdf.set_auto_page_break(auto=True, margin=15)
        self.user_name = user_name
        self.destination = destination

    def create_header(self, title: str):
        self.pdf.add_page()
        self.pdf.set_font("Arial", 'B', 16)
        self.pdf.cell(0, 10, title, ln=True, align='C')
        self.pdf.set_font("Arial", 'I', 10)
        self.pdf.cell(0, 10, f"Prepared for: {self.user_name} | Destination: {self.destination}", ln=True, align='C')
        self.pdf.cell(0, 10, f"Generated on: {datetime.now().strftime('%Y-%m-%d')}", ln=True, align='C')
        self.pdf.ln(10)

    def add_itinerary_section(self, itinerary_data: list):
        self.pdf.set_font("Arial", 'B', 14)
        self.pdf.cell(0, 10, "Trip Itinerary", ln=True)
        self.pdf.ln(5)
        
        for day in itinerary_data:
            self.pdf.set_font("Arial", 'B', 12)
            self.pdf.cell(0, 8, f"Day {day.get('Day', '')}", ln=True)
            
            self.pdf.set_font("Arial", '', 11)
            activities = ", ".join(day.get('Activities', []))
            self.pdf.multi_cell(0, 6, f"Activities: {activities}")
            
            meals = ", ".join(day.get('Meals', []))
            self.pdf.multi_cell(0, 6, f"Meals: {meals}")
            
            self.pdf.cell(0, 6, f"Estimated Cost: {day.get('EstimatedCost', '')}", ln=True)
            self.pdf.ln(5)

    def add_budget_section(self, budget_data: dict):
        self.pdf.add_page()
        self.pdf.set_font("Arial", 'B', 14)
        self.pdf.cell(0, 10, "Budget Breakdown", ln=True)
        self.pdf.ln(5)
        
        self.pdf.set_font("Arial", '', 12)
        
        items = [
            ("Total Estimated Budget", budget_data.get('TotalEstimatedBudget', 0)),
            ("Accommodation", budget_data.get('AccommodationCost', 0)),
            ("Transportation", budget_data.get('TransportationCost', 0)),
            ("Food", budget_data.get('FoodCost', 0)),
            ("Activities", budget_data.get('ActivitiesCost', 0)),
            ("Emergency Fund", budget_data.get('EmergencyFund', 0)),
        ]
        
        for name, value in items:
            self.pdf.cell(100, 8, name, border=1)
            self.pdf.cell(50, 8, f"${float(value):.2f}", border=1, ln=True, align='R')

        self.pdf.ln(10)
        self.pdf.set_font("Arial", 'I', 10)
        self.pdf.multi_cell(0, 6, "Note: These are estimated costs generated by AI. Actual costs may vary.")

    def generate_pdf(self, file_path: str = None) -> str:
        """Saves the PDF and returns the file path."""
        if not file_path:
            os.makedirs("exports", exist_ok=True)
            file_path = f"exports/{self.user_name.replace(' ', '_')}_{self.destination.replace(' ', '_')}_report.pdf"
            
        self.pdf.output(file_path)
        return file_path
